sudo: require
services:
    -docker 
    
before_install:
    - docker build -t myfirstciimage -f Dockerfile.dev .
    
script:
    - docker run -e CI=true myfirstciimage npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: " DockerReact-env"
    bicket_name: "elasticbeanstalk-us-west-2-833497906675"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
    